image: agencyicole/builder:1.0.0

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - mvn package

package:
  stage: package
  script:
    - "docker build . -t demo:latest"
