image: agencyicole/builder:1.0.0

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=/.m2/"

stages:
  - build
  - test
  - package
  - publish

build:
  stage: build
  script:
    - "mvn -Dmaven.test.skip=true package"
  artifacts:
    paths:
      - target/classes
      - target/lib

package:
  stage: package
  script:
    - "docker build . -t demo:latest"

publish:
  stage: build
  script:
    - "docker tag demo:latest agencyicole/demo:$CI_COMMIT_TAG"
    - "docker push agencyicole/demo:$CI_COMMIT_TAG"
  only:
    - tags
